# Generated by Django 4.2.2 on 2023-07-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientt',
            name='email',
        ),
    ]
