# Generated by Django 4.2.2 on 2023-06-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_client_full_name_client_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_timezone',
        ),
    ]
