# Generated by Django 4.2.2 on 2023-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_client_country_phone_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('tag', models.CharField(verbose_name='фильтр свойств клиентов, код оператора')),
                ('time_completion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_emailed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_phoned',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_permissions',
        ),
    ]
