# Generated by Django 4.2.2 on 2023-07-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_clientt_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientt',
            name='country_phone_code',
            field=models.CharField(max_length=5, verbose_name='код мобильного оператора'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing.clientt'),
        ),
    ]
