# Generated by Django 4.2.2 on 2023-07-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
    ]
