# Generated by Django 4.2.2 on 2023-07-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_mailing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientt',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientt', to='mailing.mailing'),
        ),
    ]
