# Generated by Django 4.2.2 on 2023-07-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_clientt_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
