# Generated by Django 4.2.2 on 2023-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_mailinglog_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='tag',
            field=models.CharField(default=921, max_length=3, verbose_name='Code mobile operator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.CharField(max_length=20, verbose_name='Phone of a client'),
        ),
    ]
