# Generated by Django 4.2.2 on 2023-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_mailinglog_options_mailinglog_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Mailing statistic', 'verbose_name_plural': 'Mailing statistics'},
        ),
        migrations.AlterModelOptions(
            name='mailinglog_request',
            options={'verbose_name': 'Request statistic', 'verbose_name_plural': 'Request statistics'},
        ),
    ]
